version: "3"
services:
  client:
    # file image custom được build ra từ Dockerfile theo các bước trong README.md
    image: hehe-nginx
    volumes:
      # copy toàn bộ sattic file cho vào thư mục của nginx
      # tương tự như lệnh COPY trong Dockerfile
      - ./static:/usr/share/nginx/html
    # port start sau local host là 1234
    ports:
      - "1234:80"
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80
